### ISSUE TITLE
Trying to use an open range on a non-array type causes a compiler exception

### ISSUE THREAD

**Issue by marshallsa** [microsoft/qsharp-compiler#109]
**Describe the bug**

Trying to use an open range expression (`x[1...]`) when `x` is not an array type (e.g., `Qubit` instead of `Qubit[]`) causes the compiler to throw an exception and the Visual Studio Code extension says the language server encountered an error.

```
[Error - 9:39:30 PM] 
=============================
error while running queued task
QsCompilerException: error during type checking update
QsCompilerException: error on running type checking
ArgumentException: the given expression is not of array type
Stack trace: 
   at Microsoft.Quantum.QsCompiler.SyntaxGenerator.Length(TypedExpression ex) in C:\Users\marsh\source\repos\qsharp-compiler\src\QsCompiler\Core\SyntaxGenerator.fs:line 134
   at Microsoft.Quantum.QsCompiler.SyntaxGenerator.LengthMinusOne(TypedExpression ex) in C:\Users\marsh\source\repos\qsharp-compiler\src\QsCompiler\Core\SyntaxGenerator.fs:line 140
   at Microsoft.Quantum.QsCompiler.SyntaxProcessing.Expressions.OpenEndInSlicing@604.Invoke(FSharpOption`1 _arg2) in C:\Users\marsh\source\repos\qsharp-compiler\src\QsCompiler\SyntaxProcessor\ExpressionVerification.fs:line 606
   at Microsoft.Quantum.QsCompiler.SyntaxProcessing.Expressions.resolveWith@613.Invoke(FSharpFunc`2 build, QsExpression ex) in C:\Users\marsh\source\repos\qsharp-compiler\src\QsCompiler\SyntaxProcessor\ExpressionVerification.fs:line 613
   at Microsoft.Quantum.QsCompiler.SyntaxProcessing.Expressions.rangeWithStep@608.Invoke(Tuple`3 tupledArg) in C:\Users\marsh\source\repos\qsharp-compiler\src\QsCompiler\SyntaxProcessor\ExpressionVerification.fs:line 614
   at Microsoft.Quantum.QsCompiler.SyntaxProcessing.Expressions.buildArrayItem@592.Invoke(Tuple`2 tupledArg) in C:\Users\marsh\source\repos\qsharp-compiler\src\QsCompiler\SyntaxProcessor\ExpressionVerification.fs:line 624
   at Microsoft.Quantum.QsCompiler.SyntaxProcessing.Expressions.QsExpression.Resolve[a](QsExpression this, SymbolTracker`1 symbols, FSharpFunc`2 addDiagnostic) in C:\Users\marsh\source\repos\qsharp-compiler\src\QsCompiler\SyntaxProcessor\ExpressionVerification.fs:line 814
   at Microsoft.Quantum.QsCompiler.SyntaxProcessing.Statements.VerifyWith[a,b,c](FSharpFunc`2 verification, SymbolTracker`1 symbols, QsExpression expr) in C:\Users\marsh\source\repos\qsharp-compiler\src\QsCompiler\SyntaxProcessor\StatementVerification.fs:line 29
   at Microsoft.Quantum.QsCompiler.SyntaxProcessing.Statements.Verify[a](SymbolTracker`1 symbols, QsExpression expr) in C:\Users\marsh\source\repos\qsharp-compiler\src\QsCompiler\SyntaxProcessor\StatementVerification.fs:line 36
   at Microsoft.Quantum.QsCompiler.SyntaxProcessing.Statements.NewBinding[a](QsBindingKind kind, QsComments comments, QsLocation location, SymbolTracker`1 symbols, QsSymbol qsSym, QsExpression qsExpr) in C:\Users\marsh\source\repos\qsharp-compiler\src\QsCompiler\SyntaxProcessor\StatementVerification.fs:line 173
   at Microsoft.Quantum.QsCompiler.SyntaxProcessing.Statements.NewImmutableBinding[a](QsComments comments, QsLocation location, SymbolTracker`1 symbols, QsSymbol qsSym, QsExpression qsExpr) in C:\Users\marsh\source\repos\qsharp-compiler\src\QsCompiler\SyntaxProcessor\StatementVerification.fs:line 187
   at Microsoft.Quantum.QsCompiler.CompilationBuilder.TypeChecking.<>c__DisplayClass24_0.<TryBuildLetStatement>b__0(QsLocation relPos, SymbolTracker`1 symbols) in C:\Users\marsh\source\repos\qsharp-compiler\src\QsCompiler\CompilationManager\TypeChecking.cs:line 791
   at Microsoft.Quantum.QsCompiler.CompilationBuilder.TypeChecking.BuildStatement[T](TreeNode node, Func`3 build, SymbolTracker`1 symbolTracker, List`1 diagnostics) in C:\Users\marsh\source\repos\qsharp-compiler\src\QsCompiler\CompilationManager\TypeChecking.cs:line 491
   at Microsoft.Quantum.QsCompiler.CompilationBuilder.TypeChecking.TryBuildLetStatement(IEnumerator`1 nodes, SymbolTracker`1 symbolTracker, List`1 diagnostics, Boolean& proceed, QsStatement& statement) in C:\Users\marsh\source\repos\qsharp-compiler\src\QsCompiler\CompilationManager\TypeChecking.cs:line 790
   at Microsoft.Quantum.QsCompiler.CompilationBuilder.TypeChecking.BuildStatements(IEnumerator`1 nodes, SymbolTracker`1 symbolTracker, List`1 diagnostics) in C:\Users\marsh\source\repos\qsharp-compiler\src\QsCompiler\CompilationManager\TypeChecking.cs:line 997
   at Microsoft.Quantum.QsCompiler.CompilationBuilder.TypeChecking.BuildScope(IReadOnlyList`1 nodeContent, SymbolTracker`1 symbolTracker, List`1 diagnostics) in C:\Users\marsh\source\repos\qsharp-compiler\src\QsCompiler\CompilationManager\TypeChecking.cs:line 470
   at Microsoft.Quantum.QsCompiler.CompilationBuilder.TypeChecking.BuildUserDefinedImplemenation(TreeNode root, NonNullable`1 sourceFile, QsTuple`1 argTuple, SymbolTracker`1 symbolTracker, List`1 diagnostics) in C:\Users\marsh\source\repos\qsharp-compiler\src\QsCompiler\CompilationManager\TypeChecking.cs:line 1073
   at Microsoft.Quantum.QsCompiler.CompilationBuilder.TypeChecking.<>c__DisplayClass33_0.<BuildSpecializations>g__BuildSpecialization|4(QsSpecializationKind kind, ResolvedSignature signature, QsSpecializationGeneratorKind`1 gen, TreeNode root, Func`2 buildArg, QsComments comments) in C:\Users\marsh\source\repos\qsharp-compiler\src\QsCompiler\CompilationManager\TypeChecking.cs:line 1179
   at Microsoft.Quantum.QsCompiler.CompilationBuilder.TypeChecking.<>c__DisplayClass33_0.<BuildSpecializations>g__BuildSpec|5(TreeNode root) in C:\Users\marsh\source\repos\qsharp-compiler\src\QsCompiler\CompilationManager\TypeChecking.cs:line 1202
   at System.Linq.Enumerable.SelectIListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Immutable.ImmutableArray`1.Builder.AddRange(IEnumerable`1 items)
   at Microsoft.Quantum.QsCompiler.CompilationBuilder.TypeChecking.BuildSpecializations(FragmentTree specsRoot, ResolvedSignature parentSignature, QsTuple`1 argTuple, NamespaceManager symbols, List`1 diagnostics, CancellationToken cancellationToken) in C:\Users\marsh\source\repos\qsharp-compiler\src\QsCompiler\CompilationManager\TypeChecking.cs:line 1232
   at Microsoft.Quantum.QsCompiler.CompilationBuilder.TypeChecking.<>c__DisplayClass34_1.<RunTypeChecking>g__GetSpecializations|6(KeyValuePair`2 specsRoot) in C:\Users\marsh\source\repos\qsharp-compiler\src\QsCompiler\CompilationManager\TypeChecking.cs:line 1296
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   at System.Collections.Immutable.ImmutableArray.ToImmutableArray[TSource](IEnumerable`1 items)
   at Microsoft.Quantum.QsCompiler.CompilationBuilder.TypeChecking.RunTypeChecking(CompilationUnit compilation, ImmutableDictionary`2 roots, CancellationToken cancellationToken) in C:\Users\marsh\source\repos\qsharp-compiler\src\QsCompiler\CompilationManager\TypeChecking.cs:line 1322
   at Microsoft.Quantum.QsCompiler.CompilationBuilder.TypeChecking.<>c__DisplayClass36_1.<UpdateTypeChecking>b__1() in C:\Users\marsh\source\repos\qsharp-compiler\src\QsCompiler\CompilationManager\TypeChecking.cs:line 1430
   at Microsoft.Quantum.QsCompiler.QsCompilerError.RaiseOnFailure[T](Func`1 func, String header) in C:\Users\marsh\source\repos\qsharp-compiler\src\QsCompiler\DataStructures\ErrorHandling.fs:line 59

Stack trace: 
   at Microsoft.Quantum.QsCompiler.QsCompilerError.Raise(String message, Exception innerException) in C:\Users\marsh\source\repos\qsharp-compiler\src\QsCompiler\DataStructures\ErrorHandling.fs:line 25
   at Microsoft.Quantum.QsCompiler.QsCompilerError.Raise(String message) in C:\Users\marsh\source\repos\qsharp-compiler\src\QsCompiler\DataStructures\ErrorHandling.fs:line 29
   at <StartupCode$Microsoft-Quantum-QsDataStructures>.$ErrorHandling.RaiseAndReturnNull@58-1.Invoke(String msg) in C:\Users\marsh\source\repos\qsharp-compiler\src\QsCompiler\DataStructures\ErrorHandling.fs:line 58
   at Microsoft.Quantum.QsCompiler.QsCompilerError.RaiseOnFailure[T](Func`1 func, String header) in C:\Users\marsh\source\repos\qsharp-compiler\src\QsCompiler\DataStructures\ErrorHandling.fs:line 61
   at Microsoft.Quantum.QsCompiler.CompilationBuilder.TypeChecking.UpdateTypeChecking(FileContentManager file, CompilationUnit compilation) in C:\Users\marsh\source\repos\qsharp-compiler\src\QsCompiler\CompilationManager\TypeChecking.cs:line 1430
   at Microsoft.Quantum.QsCompiler.CompilationBuilder.FileContentManager.<>c__DisplayClass66_0.<Verify>b__0() in C:\Users\marsh\source\repos\qsharp-compiler\src\QsCompiler\CompilationManager\FileContentManager.cs:line 779
   at Microsoft.Quantum.QsCompiler.QsCompilerError.RaiseOnFailure(Action action, String header) in C:\Users\marsh\source\repos\qsharp-compiler\src\QsCompiler\DataStructures\ErrorHandling.fs:line 50

Stack trace: 
   at Microsoft.Quantum.QsCompiler.QsCompilerError.Raise(String message, Exception innerException) in C:\Users\marsh\source\repos\qsharp-compiler\src\QsCompiler\DataStructures\ErrorHandling.fs:line 25
   at Microsoft.Quantum.QsCompiler.QsCompilerError.Raise(String message) in C:\Users\marsh\source\repos\qsharp-compiler\src\QsCompiler\DataStructures\ErrorHandling.fs:line 29
   at Microsoft.Quantum.QsCompiler.QsCompilerError.RaiseOnFailure(Action action, String header) in C:\Users\marsh\source\repos\qsharp-compiler\src\QsCompiler\DataStructures\ErrorHandling.fs:line 52
   at Microsoft.Quantum.QsCompiler.CompilationBuilder.FileContentManager.Verify(CompilationUnit compilation) in C:\Users\marsh\source\repos\qsharp-compiler\src\QsCompiler\CompilationManager\FileContentManager.cs:line 779
   at Microsoft.Quantum.QsCompiler.CompilationBuilder.CompilationUnitManager.<>c__DisplayClass20_0.<TriggerFileUpdateAsync>b__0() in C:\Users\marsh\source\repos\qsharp-compiler\src\QsCompiler\CompilationManager\CompilationUnitManager.cs:line 320
   at Microsoft.Quantum.QsCompiler.QsCompilerError.RaiseOnFailure(Action action, String header) in C:\Users\marsh\source\repos\qsharp-compiler\src\QsCompiler\DataStructures\ErrorHandling.fs:line 50
=============================
```

**To Reproduce**

Try this code with the language server running:

```
namespace Bug {
    operation Bug (x : Qubit) : Unit {
        let y = x[1...];
    }
}
```

**Expected behavior**

This code is invalid, so it should produce a diagnostic, but it shouldn't throw an internal compiler error.

**Screenshots**

N/A

**System information**

- Git master version
- Windows 10, .NET Core 2.2.301
- Visual Studio Code 1.37.0

**Additional context**

N/A

**Comment by bettinaheim** [comment]
Thanks for reporting! Should be a quick fix.

**Comment by bettinaheim** [comment]
Addressed with PR https://github.com/microsoft/qsharp-compiler/pull/111.
