### ISSUE TITLE
QIR generation support for Ubuntu 18.04

### ISSUE THREAD

**Issue by ltalirz** [microsoft/qsharp-compiler#1293]
**Describe the bug**

It seems to me that on Ubuntu 18.04 the QDK installs a broken `libllvm.runtime.ubuntu.20.04-x64` nuget package.

While `dotnet run` using the local simulator works fine, I get an error from `Microsoft.Quantum.QirGeneration.dll` when trying to submit to the fullstate cloud simulator.

**To Reproduce**

I'm new to Q#, so the following `Dockerfile` can probably be simplified further
``` 
FROM ubuntu:18.04

RUN apt-get update && \
  apt-get install -y wget curl

# install dotnet SDK
RUN wget https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
RUN dpkg -i packages-microsoft-prod.deb && rm packages-microsoft-prod.deb
RUN apt-get update && \
  apt-get install -y apt-transport-https && \
  apt-get install -y dotnet-sdk-3.1


# install libgomp for Quantum Simulator runtime
RUN apt-get install libgomp1

# azure cli + quantum extension (via `apt-get install azure-cli`)
RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash
RUN az extension add -n quantum

# install quantum project templates and create helloworld project
RUN dotnet new -i Microsoft.Quantum.ProjectTemplates
RUN dotnet new console -lang Q# -o runSayHello -i Microsoft.Quantum.ProjectTemplates::0.21.2112180703
``` 

Then run
```
$ docker build . -t qdk-ubu-18
$ docker run -it qdk-ubu-18 bash
root@b9fef6eb70e0:/# cd runSayHello/
root@b9fef6eb70e0:/runSayHello# dotnet run
Hello quantum world!
``` 
So far, all is working fine;
in order to reproduce my exact issue (there may be much easier ways)
```
$ az login --use-device-code
$ az account set --subscription ...
$ az quantum workspace set -g ...-l ...-w ...
$ az quantum execute --target microsoft.simulator.fullstate --
Microsoft (R) Build Engine version 16.7.2+b60ddb6f4 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored /runSayHello/runSayHello.csproj (in 682 ms).
  Determining projects to restore...
  All projects are up-to-date for restore.
/root/.nuget/packages/microsoft.quantum.qirgeneration/0.21.2112180703/lib/netstandard2.1/Microsoft.Quantum.QirGeneration.dll(1,1): error QS7017: Unable to load the file "/root/.nuget/packages/microsoft.quantum.qirgeneration/0.21.2112180703/lib/netstandard2.1/Microsoft.Quantum.QirGeneration.dll" specifying transformations to perform as part of the compilation process. The file needs to be a suitable .NET Core library. [/runSayHello/runSayHello.csproj]
  : info:
  System.DllNotFoundException: Unable to load shared library '/root/.nuget/packages/libllvm.runtime.ubuntu.20.04-x64/11.0.0/runtimes/ubuntu.20.04-x64/native/libLLVM.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libtinfo.so.6: cannot open shared object file: No such file or directory
     at System.Runtime.Loader.AssemblyLoadContext.InternalLoadUnmanagedDllFromPath(String unmanagedDllPath)
     at System.Runtime.Loader.AssemblyLoadContext.LoadUnmanagedDllFromPath(String unmanagedDllPath)
     at Microsoft.Quantum.QsCompiler.LoadContext.LoadAssembly(String path, String[] fallbackPaths)
     at Microsoft.Quantum.QsCompiler.CommandLineCompiler.CompilationOptions.<>c__DisplayClass47_0.<SetupLoadingContext>b__0(String path)
     at Microsoft.Quantum.QsCompiler.AssemblyRewriteStepsLoader.<GetLoadedSteps>g__LoadAssembly|1_0(String path)
     at Microsoft.Quantum.QsCompiler.AssemblyRewriteStepsLoader.GetLoadedSteps(IEnumerable`1 rewriteStepAssemblies)

  : info:
  System.DllNotFoundException: Unable to load shared library '/root/.nuget/packages/libllvm.runtime.ubuntu.20.04-x64/11.0.0/runtimes/ubuntu.20.04-x64/native/libLLVM.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libtinfo.so.6: cannot open shared object file: No such file or directory
     at System.Runtime.Loader.AssemblyLoadContext.InternalLoadUnmanagedDllFromPath(String unmanagedDllPath)
     at System.Runtime.Loader.AssemblyLoadContext.LoadUnmanagedDllFromPath(String unmanagedDllPath)
     at Microsoft.Quantum.QsCompiler.LoadContext.LoadAssembly(String path, String[] fallbackPaths)
     at Microsoft.Quantum.QsCompiler.CommandLineCompiler.CompilationOptions.<>c__DisplayClass47_0.<SetupLoadingContext>b__0(String path)
     at Microsoft.Quantum.QsCompiler.AssemblyRewriteStepsLoader.<GetLoadedSteps>g__LoadAssembly|1_0(String path)
     at Microsoft.Quantum.QsCompiler.AssemblyRewriteStepsLoader.GetLoadedSteps(IEnumerable`1 rewriteStepAssemblies)

/root/.nuget/packages/microsoft.quantum.csharpgeneration/0.21.2112180703/lib/netstandard2.1/Microsoft.Quantum.CSharpGeneration.dll(1,1): error QS7017: Unable to load the file "/root/.nuget/packages/microsoft.quantum.csharpgeneration/0.21.2112180703/lib/netstandard2.1/Microsoft.Quantum.CSharpGeneration.dll" specifying transformations to perform as part of the compilation process. The file needs to be a suitable .NET Core library. [/runSayHello/runSayHello.csproj]

  ____________________________________________

  Q# compilation failed: 2 errors, 0 warnings
  2 logged exceptions

/root/.nuget/packages/microsoft.quantum.sdk/0.21.2112180703/Sdk/Sdk.targets(149,5): error MSB3073: The command "dotnet "/root/.nuget/packages/microsoft.quantum.sdk/0.21.2112180703/DefaultItems/../tools/qsc/qsc.dll" build --format MsBuild -v Normal --response-files obj/qsharp/config/qsc.rsp" exited with code 24. [/runSayHello/runSayHello.csproj]
/root/.nuget/packages/microsoft.quantum.sdk/0.21.2112180703/Sdk/Sdk.targets(154,5): error : Q# compiler failed with exit code: 24. [/runSayHello/runSayHello.csproj]

Build FAILED.

/root/.nuget/packages/microsoft.quantum.qirgeneration/0.21.2112180703/lib/netstandard2.1/Microsoft.Quantum.QirGeneration.dll(1,1): error QS7017: Unable to load the file "/root/.nuget/packages/microsoft.quantum.qirgeneration/0.21.2112180703/lib/netstandard2.1/Microsoft.Quantum.QirGeneration.dll" specifying transformations to perform as part of the compilation process. The file needs to be a suitable .NET Core library. [/runSayHello/runSayHello.csproj]
/root/.nuget/packages/microsoft.quantum.csharpgeneration/0.21.2112180703/lib/netstandard2.1/Microsoft.Quantum.CSharpGeneration.dll(1,1): error QS7017: Unable to load the file "/root/.nuget/packages/microsoft.quantum.csharpgeneration/0.21.2112180703/lib/netstandard2.1/Microsoft.Quantum.CSharpGeneration.dll" specifying transformations to perform as part of the compilation process. The file needs to be a suitable .NET Core library. [/runSayHello/runSayHello.csproj]
/root/.nuget/packages/microsoft.quantum.sdk/0.21.2112180703/Sdk/Sdk.targets(149,5): error MSB3073: The command "dotnet "/root/.nuget/packages/microsoft.quantum.sdk/0.21.2112180703/DefaultItems/../tools/qsc/qsc.dll" build --format MsBuild -v Normal --response-files obj/qsharp/config/qsc.rsp" exited with code 24. [/runSayHello/runSayHello.csproj]
/root/.nuget/packages/microsoft.quantum.sdk/0.21.2112180703/Sdk/Sdk.targets(154,5): error : Q# compiler failed with exit code: 24. [/runSayHello/runSayHello.csproj]
    0 Warning(s)
    4 Error(s)

Time Elapsed 00:00:07.31
``` 

It looks like` libllvm.runtime.ubuntu.20.04-x64/11.0.0/runtimes/ubuntu.20.04-x64/native/libLLVM.so`  depends on libtinfo.so.6 which it does not find (it exists in Ubuntu 20.04 but not in 18.04).

**Expected behavior**

The QDK works on Ubuntu 18.04 (?).

**Additional context**

Related to https://github.com/MicrosoftDocs/AzureQuantumEarlyAccess/issues/18.

**Comment by ltalirz** [comment]
I have to admit that it is not entirely clear to me which versions of Ubuntu QDK officially supports.
Looking through the code [1] it seems to be 18.04 and 20.04 (?) but e.g. the azure cli [officially supports ubuntu down to 14.04](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt#overview).

If the supported Ubuntu versions differ from those of the azure cli, perhaps it would be worth mentioning this somewhere [here](https://docs.microsoft.com/en-us/azure/quantum/install-command-line-qdk#azure-cli-net-core-sdk-31-not-required)?

[1] 
``` 
$ git grep -i 20.04
examples/QIR/Development/Development.csproj:                      Include="libLLVM.runtime.ubuntu.20.04-x64" Version="11.0.0"
src/QsCompiler/TestTargets/Simulation/Target/Simulation.csproj:    <PackageReference Include="libLLVM.runtime.ubuntu.20.04-x64" Version="11.0.0" PrivateAssets="All" />
src/QsCompiler/Tests.Compiler/Tests.Compiler.fsproj:    <PackageReference Include="libLLVM.runtime.ubuntu.20.04-x64" Version="11.0.0" PrivateAssets="All" />
src/QuantumSdk/Sdk/Sdk.props:                      Include="libLLVM.runtime.ubuntu.20.04-x64" Version="11.0.0"
src/QuantumSdk/Sdk/Sdk.targets:      <LlvmLibsPath Condition="$([MSBuild]::IsOsPlatform('Linux')) And '$(UbuntuVersion)' != '18.04'">$(PkglibLLVM_runtime_ubuntu_20_04-x64)</LlvmLibsPath>
(aiidalab) a-ctalirz@cwchem-a-ctalirz:/tmp/qsharp-compiler
$ git grep -i 18.04
examples/QIR/Development/Development.csproj:    <PackageReference Condition="$([MSBuild]::IsOsPlatform('Linux')) And '$(UbuntuVersion)' == '18.04'"
examples/QIR/Development/Development.csproj:                      Include="libLLVM.runtime.ubuntu.18.04-x64" Version="11.0.0"
examples/QIR/Development/Development.csproj:    <PackageReference Condition="$([MSBuild]::IsOsPlatform('Linux')) And '$(UbuntuVersion)' != '18.04'"
src/QsCompiler/TestTargets/Simulation/Target/Simulation.csproj:    <PackageReference Include="libLLVM.runtime.ubuntu.18.04-x64" Version="11.0.0" PrivateAssets="All" />
src/QsCompiler/Tests.Compiler/Tests.Compiler.fsproj:    <PackageReference Include="libLLVM.runtime.ubuntu.18.04-x64" Version="11.0.0" PrivateAssets="All" />
src/QuantumSdk/Sdk/Sdk.props:    <PackageReference Condition="($(QirGeneration) Or $(EnableQirSubmission)) And $([MSBuild]::IsOsPlatform('Linux')) And '$(UbuntuVersion)' == '18.04'"
src/QuantumSdk/Sdk/Sdk.props:                      Include="libLLVM.runtime.ubuntu.18.04-x64" Version="11.0.0"
src/QuantumSdk/Sdk/Sdk.props:    <PackageReference Condition="($(QirGeneration) Or $(EnableQirSubmission)) And $([MSBuild]::IsOsPlatform('Linux')) And '$(UbuntuVersion)' != '18.04'"
src/QuantumSdk/Sdk/Sdk.targets:      <LlvmLibsPath Condition="$([MSBuild]::IsOsPlatform('Linux')) And '$(UbuntuVersion)' == '18.04'">$(PkglibLLVM_runtime_ubuntu_18_04-x64)</LlvmLibsPath>
src/QuantumSdk/Sdk/Sdk.targets:      <LlvmLibsPath Condition="$([MSBuild]::IsOsPlatform('Linux')) And '$(UbuntuVersion)' != '18.04'">$(PkglibLLVM_runtime_ubuntu_20_04-x64)</LlvmLibsPath>
(aiidalab) a-ctalirz@cwchem-a-ctalirz:/tmp/qsharp-compiler
$ git grep -i 16.04
```

**Comment by bettinaheim** [comment]
@ltalirz Thank you for filing the issue and pointing out that the documentation is not clear here!
The support for 18.04 is indeed limited currently. However, you should be able to submit to the cloud simulator from Ubuntu 18.04 by adding the Ubuntu version to your project file:

Please edit the project file of the project that you would like to submit to the cloud simulator to look something like this:
```
<Project Sdk="Microsoft.Quantum.Sdk/0.20.2110171573">

  <PropertyGroup>
    <UbuntuVersion>18.04</UbuntuVersion>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <ExecutionTarget>microsoft.simulators.fullstate</ExecutionTarget>
  </PropertyGroup>

</Project>
```

**Comment by ltalirz** [comment]
Thanks a lot for your help, with your suggestions I'm now able to submit from Ubuntu 18.04!

Feel free to close the issue, or to keep it open as a reminder about the local simulator/docs.

**Comment by bettinaheim** [comment]
I'll close this since I opened a separate issue for the docs.
