### ISSUE TITLE
Adjointable Operation Returns Non-Unit Causes Hard Crash Instead of Error Message

### ISSUE THREAD

**Issue by ScottCarda-MS** [microsoft/qsharp-compiler#1300]
**Describe the bug**

If an operation is incorrectly defined to be adjointable while also returning a non-unit type, the compiler gives a proper error message: "Adjoint specializations can only be defined for operations returning Unit." However, if that operation is defined and a call to that operation is used somewhere in the code. The type-checking logic seems to crash.

**To Reproduce**

Try to compile the following code:
```qsharp
namespace Input {
    @EntryPoint()
    operation Main() : Unit {
        Foo();
    }

    operation Foo() : Int is Adj {
        return 0;
    }
}
```

**Expected behavior**

The provided code should not compile, but it should fail gracefully. The compilation should provide the same behavior and error message as when the following code is attempted to be compiled:
```qsharp
namespace Input {
    @EntryPoint()
    operation Main() : Unit {
        //Foo();
    }

    operation Foo() : Int is Adj {
        return 0;
    }
}
```

**Comment by samarsha** [comment]
Does the compiler crash include an exception stack trace or some other output?

**Comment by ScottCarda-MS** [comment]
Here is a stack trace for the crashing error:
```
Microsoft.Quantum.QsCompiler.QsCompilerException: error while running global type checking
QsCompilerException: error while running type checking in background
InvalidOperationException: properties cannot be determined
Stack trace: 
   at Microsoft.Quantum.QsCompiler.SyntaxTree.ResolvedCharacteristics.GetProperties() in ...\qsharp-compiler\src\QsCompiler\DataStructures\SyntaxTree.fs:line 362
   at Microsoft.Quantum.QsCompiler.SyntaxProcessing.TypeInference.Inference.isSubset(CallableInformation info1, CallableInformation info2) in ...\qsharp-compiler\src\QsCompiler\SyntaxProcessor\TypeInference\InferenceContext.fs:line 135
   at Microsoft.Quantum.QsCompiler.SyntaxProcessing.TypeInference.InferenceContext.UnifyByOrdering(Ordering ordering, TypeContext types) in ...\qsharp-compiler\src\QsCompiler\SyntaxProcessor\TypeInference\InferenceContext.fs:line 431
   at Microsoft.Quantum.QsCompiler.SyntaxProcessing.TypeInference.InferenceContext.Unify(ResolvedType expected, ResolvedType actual) in ...\qsharp-compiler\src\QsCompiler\SyntaxProcessor\TypeInference\InferenceContext.fs:line 351
   at Microsoft.Quantum.QsCompiler.SyntaxProcessing.TypeInference.InferenceContext.ApplyConstraint(Constraint typeConstraint, ResolvedType resolvedType) in ...\qsharp-compiler\src\QsCompiler\SyntaxProcessor\TypeInference\InferenceContext.fs:line 480
   at Microsoft.Quantum.QsCompiler.SyntaxProcessing.TypeInference.InferenceContext.Constrain(ResolvedType resolvedType, Constraint typeConstraint) in ...\qsharp-compiler\src\QsCompiler\SyntaxProcessor\TypeInference\InferenceContext.fs:line 373
   at Microsoft.Quantum.QsCompiler.SyntaxProcessing.Expressions.buildCall@845.Invoke(QsExpression callable, QsExpression arg) in ...\qsharp-compiler\src\QsCompiler\SyntaxProcessor\ExpressionVerification.fs:line 860
   at Microsoft.Quantum.QsCompiler.SyntaxProcessing.Expressions.QsExpression.Resolve(QsExpression this, ScopeContext context, FSharpFunc`2 diagnose) in ...\qsharp-compiler\src\QsCompiler\SyntaxProcessor\ExpressionVerification.fs:line 935
   at Microsoft.Quantum.QsCompiler.SyntaxProcessing.Statements.resolveExpr(ScopeContext context, QsExpression expr) in ...\qsharp-compiler\src\QsCompiler\SyntaxProcessor\StatementVerification.fs:line 25
   at Microsoft.Quantum.QsCompiler.SyntaxProcessing.Statements.NewExpressionStatement(QsComments comments, QsLocation location, ScopeContext context, QsExpression expr) in ...\qsharp-compiler\src\QsCompiler\SyntaxProcessor\StatementVerification.fs:line 58
   at Microsoft.Quantum.QsCompiler.CompilationBuilder.TypeChecking.<>c__DisplayClass30_0.<TryBuildExpressionStatement>b__0(QsLocation relPos, ScopeContext ctx) in ...\qsharp-compiler\src\QsCompiler\CompilationManager\TypeChecking.cs:line 1353
   at Microsoft.Quantum.QsCompiler.CompilationBuilder.TypeChecking.BuildStatement[T](TreeNode node, Func`3 build, ScopeContext context, List`1 diagnostics) in ...\qsharp-compiler\src\QsCompiler\CompilationManager\TypeChecking.cs:line 667
   at Microsoft.Quantum.QsCompiler.CompilationBuilder.TypeChecking.TryBuildExpressionStatement(IEnumerator`1 nodes, ScopeContext context, List`1 diagnostics, Boolean& proceed, QsStatement& statement) in ...\qsharp-compiler\src\QsCompiler\CompilationManager\TypeChecking.cs:line 1351
   at Microsoft.Quantum.QsCompiler.CompilationBuilder.TypeChecking.BuildStatements(IEnumerator`1 nodes, ScopeContext context, List`1 diagnostics) in ...\qsharp-compiler\src\QsCompiler\CompilationManager\TypeChecking.cs:line 1392
   at Microsoft.Quantum.QsCompiler.CompilationBuilder.TypeChecking.BuildScope(IEnumerator`1 nodes, ScopeContext context, List`1 diagnostics, ImmutableHashSet`1 requiredFunctors) in ...\qsharp-compiler\src\QsCompiler\CompilationManager\TypeChecking.cs:line 622
   at Microsoft.Quantum.QsCompiler.CompilationBuilder.TypeChecking.BuildUserDefinedImplementation(TreeNode root, String sourceFile, QsTuple`1 argTuple, ImmutableHashSet`1 requiredFunctorSupport, ScopeContext context, List`1 diagnostics) in ...\qsharp-compiler\src\QsCompiler\CompilationManager\TypeChecking.cs:line 1500
   at Microsoft.Quantum.QsCompiler.CompilationBuilder.TypeChecking.<>c__DisplayClass34_0.<BuildSpecializations>g__BuildSpecialization|4(QsSpecializationKind kind, ResolvedSignature signature, QsSpecializationGeneratorKind`1 gen, TreeNode root, Func`2 buildArg, QsComments comments) in ...\qsharp-compiler\src\QsCompiler\CompilationManager\TypeChecking.cs:line 1672
   at Microsoft.Quantum.QsCompiler.CompilationBuilder.TypeChecking.<>c__DisplayClass34_0.<BuildSpecializations>g__BuildSpec|5(TreeNode root) in ...\qsharp-compiler\src\QsCompiler\CompilationManager\TypeChecking.cs:line 1705
   at Microsoft.Quantum.QsCompiler.Transformations.Utils.<>c__DisplayClass2_0`2.<SelectNotNull>b__0(TSource item) in ...\qsharp-compiler\src\QsCompiler\Transformations\Utils.cs:line 33
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Collections.Immutable.ImmutableArray`1.Builder.AddRange(IEnumerable`1 items)
   at Microsoft.Quantum.QsCompiler.Transformations.Utils.Apply[T](T x, Action`1 f) in ...\qsharp-compiler\src\QsCompiler\Transformations\Utils.cs:line 18
   at Microsoft.Quantum.QsCompiler.CompilationBuilder.TypeChecking.BuildSpecializations(FragmentTree specsRoot, ResolvedSignature parentSignature, QsTuple`1 argTuple, CompilationUnit compilation, List`1 diagnostics, CancellationToken cancellationToken) in ...\qsharp-compiler\src\QsCompiler\CompilationManager\TypeChecking.cs:line 1758
   at Microsoft.Quantum.QsCompiler.CompilationBuilder.TypeChecking.<>c__DisplayClass35_1.<RunTypeChecking>g__GetSpecializations|6(KeyValuePair`2 specsRoot) in ...\qsharp-compiler\src\QsCompiler\CompilationManager\TypeChecking.cs:line 1841
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.ToArray()
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   at Microsoft.Quantum.QsCompiler.CompilationBuilder.TypeChecking.RunTypeChecking(CompilationUnit compilation, ImmutableDictionary`2 roots, CancellationToken cancellationToken) in ...\qsharp-compiler\src\QsCompiler\CompilationManager\TypeChecking.cs:line 1884
   at Microsoft.Quantum.QsCompiler.CompilationBuilder.CompilationUnitManager.<>c__DisplayClass43_0.<RunGlobalTypeChecking>b__0() in ...\qsharp-compiler\src\QsCompiler\CompilationManager\CompilationUnitManager.cs:line 679
   at Microsoft.Quantum.QsCompiler.QsCompilerError.RaiseOnFailure[T](Func`1 func, String header) in ...\qsharp-compiler\src\QsCompiler\DataStructures\ErrorHandling.fs:line 74

Stack trace: 
   at Microsoft.Quantum.QsCompiler.QsCompilerError.Raise(String message, Exception innerException) in ...\qsharp-compiler\src\QsCompiler\DataStructures\ErrorHandling.fs:line 29
   at Microsoft.Quantum.QsCompiler.QsCompilerError.Raise(String message) in ...\qsharp-compiler\src\QsCompiler\DataStructures\ErrorHandling.fs:line 34
   at <StartupCode$Microsoft-Quantum-QsDataStructures>.$ErrorHandling.RaiseAndReturnNull@69-1.Invoke(String msg) in ...\qsharp-compiler\src\QsCompiler\DataStructures\ErrorHandling.fs:line 70
   at Microsoft.Quantum.QsCompiler.QsCompilerError.RaiseOnFailure[T](Func`1 func, String header) in ...\qsharp-compiler\src\QsCompiler\DataStructures\ErrorHandling.fs:line 77
   at Microsoft.Quantum.QsCompiler.CompilationBuilder.CompilationUnitManager.RunGlobalTypeChecking(CompilationUnit compilation, ImmutableDictionary`2 content, CancellationToken cancellationToken) in ...\qsharp-compiler\src\QsCompiler\CompilationManager\CompilationUnitManager.cs:line 678
   at Microsoft.Quantum.QsCompiler.CompilationBuilder.CompilationUnitManager.<>c__DisplayClass42_0.<SpawnGlobalTypeCheckingAsync>b__5() in ...\qsharp-compiler\src\QsCompiler\CompilationManager\CompilationUnitManager.cs:line 643
   at Microsoft.Quantum.QsCompiler.QsCompilerError.RaiseOnFailure(Action action, String header) in ...\qsharp-compiler\src\QsCompiler\DataStructures\ErrorHandling.fs:line 60

   at Microsoft.Quantum.QsCompiler.QsCompilerError.Raise(String message, Exception innerException) in ...\qsharp-compiler\src\QsCompiler\DataStructures\ErrorHandling.fs:line 29
   at Microsoft.Quantum.QsCompiler.QsCompilerError.Raise(String message) in ...\qsharp-compiler\src\QsCompiler\DataStructures\ErrorHandling.fs:line 34
   at Microsoft.Quantum.QsCompiler.QsCompilerError.RaiseOnFailure(Action action, String header) in ...\qsharp-compiler\src\QsCompiler\DataStructures\ErrorHandling.fs:line 63
   at Microsoft.Quantum.QsCompiler.CompilationBuilder.CompilationUnitManager.<>c__DisplayClass42_0.<SpawnGlobalTypeCheckingAsync>b__3() in ...\qsharp-compiler\src\QsCompiler\CompilationManager\CompilationUnitManager.cs:line 642
```

**Comment by samarsha** [comment]
OK, it looks like `isSubset` crashes when one of the characteristics is invalid. Probably it should work like `characteristicsEqual` and return true if one of them is invalid.
