### ISSUE TITLE
Cannot access UDT items from a lambda parameter

### ISSUE THREAD

**Issue by msoeken** [microsoft/qsharp-compiler#1380]
**Describe the bug**

Describe what the unexpected behavior or issue is. 
Please file a single issue per bug instead of enumerating multiple items.

Q# compiler does not compile a lambda that involves UDT entry access.

**To Reproduce**

The following program fails to compile:

```qsharp
namespace Project {
    open Microsoft.Quantum.Arrays;

    newtype Gate = (Control: Int, Target: Int);

    internal function GateControl(gate : Gate) : Int {
        return gate::Control;
    }

    function GetControls() : Int[] {
        let gates = [Gate(0, 0), Gate(1, 1), Gate(2, 2)];
        return Mapped(gate -> gate::Control, gates);
        // return Mapped(GateControl, gates); // this works
    }

    @EntryPoint()
    operation RunProgram() : Unit {}
}
```

**Expected behavior**

Should compile, as with the commented out line, which works.

**Screenshots**

Output:

```
Microsoft (R) Build Engine version 16.7.2+b60ddb6f4 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  Determining projects to restore...
  All projects are up-to-date for restore.
./Program.qs(12,32): error QS5016: The type of the expression needs to be a user defined type. The given expression is of type 'f. [./test.csproj]
  : info: 
  System.ArgumentException: Unsupported QsExpressionKind Lambda
    { kind = Function
      paramTuple =
                  QsTuple
                    (seq
                       [QsTupleItem
                          { VariableName = ValidName "gate"
                            Type =
                                  { kind = UserDefinedType { Namespace = "Project"
                                                             Name = "Gate"
                                                             Range = Null }
                                    range =
                                           Inferred
                                             (Range
                                                (Position (0,14),Position (0,18))) }
                            InferredInformation =
                                                 { IsMutable = false
                                                   HasLocalQuantumDependency =
                                                                              false }
                            Position = Value (Position (2,8))
                            Range = Range (Position (0,14),Position (0,18)) }])
      body =
            { Expression =
                          NamedItem
                            ({ Expression = Identifier (LocalVariable "gate",Null)
                               TypeArguments = seq []
                               ResolvedType =
                                             { kind =
                                                     UserDefinedType
                                                       { Namespace = "Project"
                                                         Name = "Gate"
EXEC(1,1): error QS7106: Unable to serialize the built compilation. [./test.csproj]
                                                         Range = Null }
                                               range =
                                                      Inferred
                                                        (Range
                                                           (Position (0,23),
                                                            Position (0,27))) }
                               InferredInformation =
                                                    { IsMutable = false
                                                      HasLocalQuantumDependency =
                                                                                 false }
                               Range =
                                      Value
                                        (Range (Position (0,23),Position (0,27))) },
                             LocalVariable "Control")
              TypeArguments = seq []
              ResolvedType = { kind = InvalidType
                               range = Generated }
              InferredInformation = { IsMutable = false
                                      HasLocalQuantumDependency = false }
              Range = Value (Range (Position (0,23),Position (0,36))) } }
     at Microsoft.Quantum.QsCompiler.BondSchemas.BondSchemaTranslator.ToBondSchemaGeneric[TBondExpression,TBondSymbol,TBondType,TCompilerExpression,TCompilerSymbol,TCompilerType](QsExpressionKind`3 qsExpressionKind, Func`2 expressionTranslator, Func`2 symbolTranslator, Func`2 typeTranslator)
     at Microsoft.Quantum.QsCompiler.BondSchemas.BondSchemaTranslator.ToBondSchema(QsExpressionKind`3 qsExpressionKind)
     at Microsoft.Quantum.QsCompiler.BondSchemas.BondSchemaTranslator.ToBondSchema(TypedExpression typedExpression)
     at Microsoft.Quantum.QsCompiler.BondSchemas.BondSchemaTranslator.<>c__DisplayClass56_0`6.<ToBondSchemaGeneric>b__0(TCompilerExpression v)
     at System.Linq.Enumerable.SelectArrayIterator`2.ToList()
     at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
     at Microsoft.Quantum.QsCompiler.BondSchemas.BondSchemaTranslator.ToBondSchemaGeneric[TBondExpression,TBondSymbol,TBondType,TCompilerExpression,TCompilerSymbol,TCompilerType](QsExpressionKind`3 qsExpressionKind, Func`2 expressionTranslator, Func`2 symbolTranslator, Func`2 typeTranslator)
     at Microsoft.Quantum.QsCompiler.BondSchemas.BondSchemaTranslator.ToBondSchema(QsExpressionKind`3 qsExpressionKind)
     at Microsoft.Quantum.QsCompiler.BondSchemas.BondSchemaTranslator.ToBondSchema(TypedExpression typedExpression)
     at Microsoft.Quantum.QsCompiler.BondSchemas.BondSchemaTranslator.ToQsExpressionKindExpressionDoubleGeneric[TBond,TCompiler](TCompiler expression1, TCompiler expression2, Func`2 typeTranslator)
     at Microsoft.Quantum.QsCompiler.BondSchemas.BondSchemaTranslator.ToBondSchemaGeneric[TBondExpression,TBondSymbol,TBondType,TCompilerExpression,TCompilerSymbol,TCompilerType](QsExpressionKind`3 qsExpressionKind, Func`2 expressionTranslator, Func`2 symbolTranslator, Func`2 typeTranslator)
     at Microsoft.Quantum.QsCompiler.BondSchemas.BondSchemaTranslator.ToBondSchema(QsExpressionKind`3 qsExpressionKind)
     at Microsoft.Quantum.QsCompiler.BondSchemas.BondSchemaTranslator.ToBondSchema(TypedExpression typedExpression)
     at Microsoft.Quantum.QsCompiler.BondSchemas.BondSchemaTranslator.ToBondSchema(QsStatementKind qsStatementKind)
     at Microsoft.Quantum.QsCompiler.BondSchemas.BondSchemaTranslator.ToBondSchema(QsStatement qsStatement)
     at Microsoft.Quantum.QsCompiler.BondSchemas.BondSchemaTranslator.<>c.<ToBondSchema>b__32_0(QsStatement s)
     at System.Linq.Enumerable.SelectArrayIterator`2.ToList()
     at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
     at Microsoft.Quantum.QsCompiler.BondSchemas.BondSchemaTranslator.ToBondSchema(QsScope qsScope)
     at Microsoft.Quantum.QsCompiler.BondSchemas.BondSchemaTranslator.ToSpecializationImplementationKindProvided(QsTuple`1 tuple, QsScope implementation)
     at Microsoft.Quantum.QsCompiler.BondSchemas.BondSchemaTranslator.ToBondSchema(SpecializationImplementation specializationImplementation)
     at Microsoft.Quantum.QsCompiler.BondSchemas.BondSchemaTranslator.ToBondSchema(QsSpecialization qsSpecialization)
     at Microsoft.Quantum.QsCompiler.BondSchemas.BondSchemaTranslator.<>c.<ToBondSchema>b__10_1(QsSpecialization s)
     at System.Linq.Enumerable.SelectArrayIterator`2.ToList()
     at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
     at Microsoft.Quantum.QsCompiler.BondSchemas.BondSchemaTranslator.ToBondSchema(QsCallable qsCallable)
     at Microsoft.Quantum.QsCompiler.BondSchemas.BondSchemaTranslator.ToBondSchema(QsNamespaceElement qsNamespaceElement)
     at Microsoft.Quantum.QsCompiler.BondSchemas.BondSchemaTranslator.<>c.<ToBondSchema>b__24_0(QsNamespaceElement e)
     at System.Linq.Enumerable.SelectArrayIterator`2.ToList()
     at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
     at Microsoft.Quantum.QsCompiler.BondSchemas.BondSchemaTranslator.ToBondSchema(QsNamespace qsNamespace)
     at Microsoft.Quantum.QsCompiler.BondSchemas.BondSchemaTranslator.<>c.<CreateBondCompilation>b__0_0(QsNamespace n)
     at System.Linq.Enumerable.SelectArrayIterator`2.ToList()
     at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
     at Microsoft.Quantum.QsCompiler.BondSchemas.BondSchemaTranslator.CreateBondCompilation(QsCompilation qsCompilation)
     at Microsoft.Quantum.QsCompiler.BondSchemas.Protocols.SerializeQsCompilationToSimpleBinary(QsCompilation qsCompilation, Stream stream)
     at Microsoft.Quantum.QsCompiler.CompilationLoader.SerializeSyntaxTree(QsCompilation syntaxTree, Stream stream, Action`1 onException)
  
  
  ____________________________________________
  
  Q# compilation failed: 2 errors, 0 warnings 
  1 logged exception
  
...

Build FAILED.
```

**System information**

- Version of the NuGet package or extension for which the problem occurs: 0.23.195983
- Your operating system and .NET Core version: macOS 12.2.1, .NET 3.1.405

**Comment by samarsha** [comment]
Type inference currently doesn't have support for type constraints on UDT named items - that was out of scope of the original implementation, and it's expected that some lambdas may require type annotations, so relabeling this as an enhancement. I agree that it would be nice to support this case though.
