### ISSUE TITLE
Q# Language Server encounters ArgumentOutOfRangeException while editing a file

### ISSUE THREAD

**Issue by rhpreston** [microsoft/qsharp-compiler#387]
**Describe the bug**

While working on a Q# project, the following banner will pop up, seemingly at random:

```
The Q# Language Server has encountered an error. Diagnostics will be reloaded upon saving the file. Details on the encountered error have been logged to the output window.
```

Subsequently, more identical banners pop up for each character I type, until I save the file and there's a chance it will stop.

Checking the output, the detailed error message is:

```
Error: 
=============================
Microsoft.Quantum.QsCompiler.QsCompilerException: error while running queued task
QsCompilerException: error during scope tracking update
ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'startChar')
Stack trace: 
   at Microsoft.Quantum.QsCompiler.CompilationBuilder.Utils.GetChangedText(String lineText, Int32 startChar, Int32 endChar, String insert)
   at Microsoft.Quantum.QsCompiler.CompilationBuilder.FileContentManager.DequeueUnprocessedChanges(Int32& lineNr, String& textToInsert)
   at Microsoft.Quantum.QsCompiler.CompilationBuilder.ScopeTracking.UpdateScopeTacking(FileContentManager file, TextDocumentContentChangeEvent change)
   at Microsoft.Quantum.QsCompiler.QsCompilerError.RaiseOnFailure(Action action, String header)

Stack trace: 
   at Microsoft.Quantum.QsCompiler.QsCompilerError.Raise(String message, Exception innerException)
   at Microsoft.Quantum.QsCompiler.QsCompilerError.RaiseOnFailure(Action action, String header)
   at Microsoft.Quantum.QsCompiler.CompilationBuilder.FileContentManager.Update(TextDocumentContentChangeEvent change)
   at Microsoft.Quantum.QsCompiler.CompilationBuilder.CompilationUnitManager.<>c__DisplayClass19_0.<SourceFileDidChangeAsync>b__0()
   at Microsoft.Quantum.QsCompiler.QsCompilerError.RaiseOnFailure(Action action, String header)

   at Microsoft.Quantum.QsCompiler.QsCompilerError.Raise(String message, Exception innerException)
   at Microsoft.Quantum.QsCompiler.QsCompilerError.RaiseOnFailure(Action action, String header)
   at Microsoft.Quantum.QsCompiler.CompilationBuilder.ProcessingQueue.<>c__DisplayClass4_0.<ProcessingTaskAsync>b__0()
=============================
```

**To Reproduce**

Since I don't know exactly what is causing this, it is difficult to say how to reproduce it. For me, it is certain to happen at least once within an hour of development.

**System information**

- Version of the NuGet package or extension for which the problem occurs
  **0.10.2002.2610**

- Your operating system and .NET Core version
```
> dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.102
 Commit:    573d158fea

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.102\

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26
...
```

- For issues with extensions, the version of the IDE for which the problem occurs 
  **Visual Studio Enterprise 2019 version 16.5.0**

**Comment by bettinaheim** [comment]
@rhpreston  These sporadic issues seem to have popped up with some of the latest VisualStudio update. Since we didn't change anything on our end, I suspect it might be out of our hands. I'll try to follow up with our VS team.

**Comment by bettinaheim** [comment]
@rhpreston
I did hear back from the VS team, and they are investigating an issue where messages sent from the client could be out of order. This would indeed exactly cause the issue above, given that we do an incremental compilation and thus rely on the correct ordering. 
Waiting for a second, then saving and giving it another second should usually get rid of the immediate issue. I will do a modification to the error handling to not spam you with so many errors. My apologies for the inconvenience, and I unfortunately do not currently have a time line regarding when that issue might be addressed. Earlier VS versions (pre 16.5 I think) as well as our VS Code extension should be fine.

**Comment by rhpreston** [comment]
Haven't encountered this problem for some time, closing
