### ISSUE TITLE
Error when running dotnet run on hello world template

### ISSUE THREAD

**Issue by Volnetiks** [microsoft/qsharp-compiler#832]
**Describe the bug**

Cannot run the hello world application due to dotnet run error

**To Reproduce**

I dont think I did anything wrong, so I dont really know, but it happens on all my projects

**Expected behavior**

Expecting "Hello quantum world!" in console.

**Screenshots**

![Capture](https://user-images.githubusercontent.com/38158984/105618140-5088c780-5de4-11eb-913e-038f226313aa.PNG)

**System information**

Operating System: Windows 10 20H2
.NET Core Version: 3.4.405

**Comment by Volnetiks** [comment]
Also, I get the error "The Q# Language Server has encountered an error. Diagnostics will be reloaded upon saving the file. Details on the encountered error have been logged to the output window."

And the error in the output window is

```Microsoft.Quantum.QsCompiler.QsCompilerException: error while running queued task
BadImageFormatException: Could not load file or assembly 'Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. An attempt was made to load a program with an incorrect format.
Stack trace: 
   at Microsoft.Quantum.QsLanguageServer.EditorState.QsProjectLoader(Uri projectFile, ProjectInformation& info)
   at Microsoft.Quantum.QsCompiler.CompilationBuilder.ProjectManager.<>c__DisplayClass11_0.<LoadProjectsAsync>b__1() in D:\a\1\s\submodules\qsharp-compiler\src\QsCompiler\CompilationManager\ProjectManager.cs:line 735
   at Microsoft.Quantum.QsCompiler.QsCompilerError.RaiseOnFailure(Action action, String header) in D:\a\1\s\submodules\qsharp-compiler\src\QsCompiler\DataStructures\ErrorHandling.fs:line 54

   at Microsoft.Quantum.QsCompiler.QsCompilerError.Raise(String message, Exception innerException) in D:\a\1\s\submodules\qsharp-compiler\src\QsCompiler\DataStructures\ErrorHandling.fs:line 27
   at Microsoft.Quantum.QsCompiler.QsCompilerError.RaiseOnFailure(Action action, String header) in D:\a\1\s\submodules\qsharp-compiler\src\QsCompiler\DataStructures\ErrorHandling.fs:line 56
   at Microsoft.Quantum.QsCompiler.CompilationBuilder.ProcessingQueue.<>c__DisplayClass4_0.<ProcessingTaskAsync>b__0() in D:\a\1\s\submodules\qsharp-compiler\src\QsCompiler\CompilationManager\ProcessingQueue.cs:line 42```

**Comment by Volnetiks** [comment]
Somehow, reinstalling dotnet worked, closing this

**Comment by samarsha** [comment]
Thanks for the update, glad it was resolved!
