### ISSUE TITLE
Q# Language Server fails to initialize in Visual Studio due to JsonReaderException

### ISSUE THREAD

**Issue by rhpreston** [microsoft/qsharp-compiler#885]
**Describe the bug**

Q# Language Extension crashes on startup and prints the following error message:

```
Server initialization failed.
Path to the language server executable: "C:\USERS\RHPRESTON\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\16.0_F5555D13\EXTENSIONS\1JSHGQDM.XVS\LanguageServer\Microsoft.Quantum.QsLanguageServer.exe"
Path to the log file: "C:\Users\rhpreston\AppData\Local\Temp\qsp-637503055320695624.log"
StreamJsonRpc.RemoteInvocationException: could not cast given JToken
JsonReaderException: Error reading boolean. Unexpected token: StartObject. Path 'capabilities.textDocument.publishDiagnostics.tagSupport'.
Stack trace: 
   at Newtonsoft.Json.JsonReader.ReadAsBoolean()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at Microsoft.Quantum.QsLanguageServer.Utils.<>c__DisplayClass0_0`1.<TryJTokenAs>b__0()
   at Microsoft.Quantum.QsCompiler.QsCompilerError.RaiseOnFailure[T](Func`1 func, String header)

   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__139`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.LanguageServer.Client.JsonRpcExtensionMethods.<SendMethodRequestAsync>d__1`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.VisualStudio.LanguageServer.Client.RemoteLanguageClientInstance.<InitializeAsync>d__83.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.LanguageServer.Client.RemoteLanguageClientInstance.<InitializeAsync>d__83.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.ThreadingTools.<WithCancellationSlow>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.LanguageServer.Client.RemoteLanguageClientInstance.<ActivateLanguageClientAsync>d__89.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
RPC server exception:
Microsoft.Quantum.QsCompiler.QsCompilerException: could not cast given JToken
JsonReaderException: Error reading boolean. Unexpected token: StartObject. Path 'capabilities.textDocument.publishDiagnostics.tagSupport'.
Stack trace: 
   at Newtonsoft.Json.JsonReader.ReadAsBoolean()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at Microsoft.Quantum.QsLanguageServer.Utils.<>c__DisplayClass0_0`1.<TryJTokenAs>b__0()
   at Microsoft.Quantum.QsCompiler.QsCompilerError.RaiseOnFailure[T](Func`1 func, String header)

      at Microsoft.Quantum.QsCompiler.QsCompilerError.Raise(String message, Exception innerException)
      at Microsoft.Quantum.QsCompiler.QsCompilerError.RaiseOnFailure[T](Func`1 func, String header)
      at Microsoft.Quantum.QsLanguageServer.Utils.TryJTokenAs[T](JToken arg)
      at Microsoft.Quantum.QsLanguageServer.QsLanguageServer.Initialize(JToken arg)
```

Contents of log file:

```
Connecting via named pipe. 
ReaderPipe: "QsLanguageServerReaderPipe637503055320695624" 
WriterPipe:"QsLanguageServerWriterPipe637503055320695624"
Listening...
Exiting normally.
```

**To Reproduce**

1. Create a new Q# Test Project.
2. The Q# Language Server fails to initialize.

**Expected behavior**

The Q# Language Server works with no errors.

**System information**

- Version of the NuGet package or extension for which the problem occurs:
    - QDK Extension Version 0.15.2102.129448
- Your operating system and .NET Core version
    - Windows 10 1909 18363.1377
    - .NET Version 3.1.406
- For issues with extensions, the version of the IDE for which the problem occurs:
    - Visual Studio Enterprise 2019 Version 16.9.0

**Additional context**

Got the same behavior on a fresh Q# Application Project.

**Comment by cgranade** [comment]
Thanks for reporting, @rhpreston! I'm not able to reproduce this on 16.8.* versions of Visual Studio, such that this may be a regression with the latest update; let me take a look and see what I can figure out there.

@samarsha, @bettinaheim: at first glance, it looks like this exception is caused by the language server not handling JSON that doesn't match the right schema for LSP. Is there a way to see what JSON caused the problem? Thanks!

**Comment by rhpreston** [comment]
Agree, it just started happening after I updated to 16.9.0, so that's likely the culprit. (Sorry should have mentioned this!)

**Comment by cgranade** [comment]
> Agree, it just started happening after I updated to 16.9.0, so that's likely the culprit. (Sorry should have mentioned this!)

No worries, thanks for letting us know, that's really helpful! Let me continue looking into things on my side, but in the meantime thanks for the report and the additional info!

**Comment by cgranade** [comment]
I can confirm that I get this as well with 16.9.0, thanks again for raising this!

**Comment by ricardo-espinoza** [comment]
Hotfix in progress to resolve this issue. Will mark as Open until the release is available.

**Comment by raffaeleterribile** [comment]
I have the same error, both with Visual Studio 16.9.2 and with Visual Studio Code 1.54.3.
Today I tried to compile the sources (witj the instructions at https://github.com/microsoft/qsharp-compiler) and to use the recompiled version to compile a Q# project, but I cannot resolve the issue.
The error will be resolved in the next release? And when it's planned the next release?
I cannot debug my Q# applications...

**Comment by cgranade** [comment]
Thanks for the report, @raffaeleterribile! We believe the fix that @ricardo-espinoza mentioned above should fix the issue, such that you should be able to use VS 16.9.2 starting with the next release. Thanks for your patience!

**Comment by raffaeleterribile** [comment]
Thank you very much for your reply.
Did you know when will be relesaed the next version?

**Comment by rhpreston** [comment]
Working with Visual Studio 16.9.3 and QDK 0.15.2103.133969
